"""Update Appearance with foreign keys and validation

Revision ID: 08cb9229fd84
Revises: 7adc741d5c82
Create Date: 2025-06-23 14:56:21.431415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08cb9229fd84'
down_revision = '7adc741d5c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('appearances_episode_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('appearances_guest_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'guests', ['guest_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'episodes', ['episode_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('appearances_guest_id_fkey'), 'guests', ['guest_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('appearances_episode_id_fkey'), 'episodes', ['episode_id'], ['id'])

    # ### end Alembic commands ###
